apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/gateway.yaml
  - manifests/pvc.yaml
  - manifests/service.yaml

  - db/statefulset.yaml

  - pong/manifests/service.yaml
  - pong/manifests/deployment.yaml

images:
  - name: READER_IMAGE
    newName: mluukkai/log_output_reader:9
  - name: WRITER_IMAGE
    newName: mluukkai/log_output_writer:3
  - name: PONGER_IMAGE
    newName: mluukkai/pingpong:6
