apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/configmap.yaml
- manifests/route.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- db/statefulset.yaml
- pong/manifests/service.yaml
- pong/manifests/deployment.yaml
- root/manifests/service.yaml
- root/manifests/deployment.yaml

images:
- name: PONGER_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/ponger
  newTag: main-158bd5419af28d0e7c96c6ecc39a232109e78ccd
- name: READER_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/reader
  newTag: main-158bd5419af28d0e7c96c6ecc39a232109e78ccd
- name: ROOTTI_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/rootti
  newTag: main-158bd5419af28d0e7c96c6ecc39a232109e78ccd
- name: ROOT_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-root
  newTag: main-38fa7881d29ebdd4d32bfa303e10273cfc78f52b
- name: WRITER_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/writer
  newTag: main-158bd5419af28d0e7c96c6ecc39a232109e78ccd
