apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-stset
  namespace: exercises
spec:
  serviceName: psql-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: psql-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: psql-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: psql-svc
  namespace: exercises  
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres

# psql postgres://psql-svc:5432 -U postgres
# kubectl run -it --rm --restart=Never --image postgres psql-for-debugging sh