apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-root-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app-root
  template:
    metadata:
      labels:
        app: log-app-root
    spec:  
      containers:
      - name: log-app-root
        image: ROOT_IMAGE
